import { mkdtempSync,mkdirSync,writeFileSync } from 'node:fs';import { execFileSync } from 'node:child_process';import { join } from 'node:path';import { tmpdir } from 'node:os';import { describe,expect,it } from 'vitest';import { EventStore } from '../packages/event-store/src/index.ts';import { GraphRuntime } from '../packages/graph-runtime/src/index.ts';import { createDemoSpec } from '../packages/graph-runtime/src/demo.ts';
const setup=()=>{const root=mkdtempSync(join(tmpdir(),'graph-runtime-')),repository=join(root,'repo');mkdirSync(join(repository,'src/runtime'),{recursive:true});mkdirSync(join(repository,'src/dashboard'),{recursive:true});writeFileSync(join(repository,'package.json'),'{"scripts":{"test":"node --test"}}');writeFileSync(join(repository,'test.mjs'),"import test from 'node:test';import assert from 'node:assert/strict';test('ok',()=>assert.ok(true));\n");writeFileSync(join(repository,'src/runtime/index.ts'),'export const ready=true;\n');writeFileSync(join(repository,'src/dashboard/index.ts'),'export const ready=true;\n');for(const [command,args] of [['git',['init','-b','main']],['git',['config','user.email','test@example.test']],['git',['config','user.name','Test']],['git',['add','.']],['git',['commit','-m','base']]] as const)execFileSync(command,[...args],{cwd:repository,stdio:'ignore'});const store=new EventStore(join(root,'db.sqlite')),projectId=store.createProject(repository),spec=createDemoSpec(repository),published=store.publishGraph(projectId,spec);store.approve(published.graphVersionId);return {root,store,projectId,spec,published}};
async function waitFor(store:EventStore,runId:string,status:string[],timeout=5_000){const started=Date.now();while(Date.now()-started<timeout){const row=store.getRun(runId);if(status.includes(row?.status))return row;await new Promise(resolve=>setTimeout(resolve,20))}throw new Error(`Timed out waiting for ${status.join(',')}`)}
describe('graph runtime',()=>{
  it('retries a rejected node and completes',async()=>{const ctx=setup(),runtime=new GraphRuntime(ctx.store),runId=await runtime.start(ctx.projectId,ctx.published.graphId,ctx.published.graphVersionId,ctx.spec);const run=await waitFor(ctx.store,runId,['completed']);const events=ctx.store.eventsAfter(runId);expect(run.state.artifactIndex['run-report.json']).toBeTruthy();expect(events.some(event=>event.type==='node.retry.scheduled')).toBe(true);ctx.store.close()});
  it('uses a fresh verifier session',async()=>{const ctx=setup(),runtime=new GraphRuntime(ctx.store),runId=await runtime.start(ctx.projectId,ctx.published.graphId,ctx.published.graphVersionId,ctx.spec);await waitFor(ctx.store,runId,['completed']);const sessions=ctx.store.db.prepare("SELECT id,role FROM agent_sessions WHERE run_id=? AND node_id='implement_runtime'").all(runId) as {id:string;role:string}[];expect(new Set(sessions.map(x=>x.role))).toEqual(new Set(['worker','verifier']));expect(new Set(sessions.map(x=>x.id)).size).toBe(sessions.length);ctx.store.close()});
  it('times out a delayed node',async()=>{const ctx=setup();ctx.spec.nodes[0]!.objective+=' [delay]';ctx.spec.nodes[0]!.timeoutSeconds=1;const runtime=new GraphRuntime(ctx.store),runId=await runtime.start(ctx.projectId,ctx.published.graphId,ctx.published.graphVersionId,ctx.spec);expect((await waitFor(ctx.store,runId,['failed'],4_000)).status).toBe('failed');ctx.store.close()});
  it('cancels an active run',async()=>{const ctx=setup();ctx.spec.nodes[0]!.objective+=' [delay]';const runtime=new GraphRuntime(ctx.store),runId=await runtime.start(ctx.projectId,ctx.published.graphId,ctx.published.graphVersionId,ctx.spec);await new Promise(resolve=>setTimeout(resolve,50));runtime.cancel(runId);expect((await waitFor(ctx.store,runId,['cancelled'])).state.finalStatus).toBe('cancelled');ctx.store.close()});
  it('resumes persisted state without repeating completed nodes',async()=>{const ctx=setup(),runId='run_restart',state={runId,graphVersion:ctx.published.graphVersionId,repoRef:'main',nodeIndex:Object.fromEntries(ctx.spec.nodes.map(node=>[node.id,node.id==='analyze_repo'?'succeeded':'pending'])),artifactIndex:{'repo-map.json':ctx.store.writeArtifact(runId,'analyze_repo','repo-map.json','{}')},budgetState:{startedAt:new Date().toISOString(),attempts:1},decisionFlags:{approved:true},finalStatus:'running'};ctx.store.createRun(ctx.published.graphId,ctx.published.graphVersionId,state);const runtime=new GraphRuntime(ctx.store);await runtime.resume(ctx.projectId,runId,ctx.spec);await waitFor(ctx.store,runId,['completed']);expect(ctx.store.eventsAfter(runId).some(event=>event.nodeId==='analyze_repo')).toBe(false);ctx.store.close()});
});
