import type { GraphSpec } from "./types.ts";

export const fallbackSpec: GraphSpec = {
  goal: "Ship Graph Engineer vertical slice",
  goalCharter: {
    strategic:
      "Ship the vertical slice without sacrificing human approval, auditability, or frozen acceptance.",
    medium:
      "Integration survives adversarial review on cross-module diff evidence, not only scoped unit tests.",
    fast:
      "Parallel runtime and dashboard workers complete with passing scoped tests and named artifacts.",
  },
  version: "1.0",
  policies: { maxParallel: 2 },
  nodes: [
    {
      id: "analyze_repo",
      title: "Map repository",
      kind: "analysis",
      objective: "Inspect rules, commands and module boundaries.",
      agentSelector: { preferredAgents: ["Codex"] },
      workspace: { mode: "readonly", readGlobs: ["**"], writeGlobs: [] },
      inputs: ["repo"],
      outputs: [{ name: "repo-map.json", type: "json" }],
      acceptanceChecks: [
        { type: "artifact", description: "Map exists", frozen: true },
      ],
      retryPolicy: { maxAttempts: 1 },
      timeoutSeconds: 20,
      verifierPolicy: { required: false, freshSession: true, readonly: true },
    },
    {
      id: "implement_runtime",
      title: "Runtime & recovery",
      kind: "worker",
      objective: "Persist scheduling, retries and checkpoints.",
      agentSelector: { preferredAgents: ["Claude"] },
      workspace: {
        mode: "worktree",
        readGlobs: ["**"],
        writeGlobs: ["packages/graph-runtime/**"],
      },
      inputs: ["repo-map.json"],
      outputs: [{ name: "runtime.patch", type: "git_patch" }],
      acceptanceChecks: [
        {
          type: "command",
          command: "pnpm test runtime",
          description: "Tests",
          frozen: true,
        },
      ],
      retryPolicy: { maxAttempts: 2 },
      timeoutSeconds: 120,
      verifierPolicy: { required: true, freshSession: true, readonly: true },
    },
    {
      id: "implement_dashboard",
      title: "Review dashboard",
      kind: "worker",
      objective: "Build graph review and live run evidence.",
      agentSelector: { preferredAgents: ["Codex"] },
      workspace: {
        mode: "worktree",
        readGlobs: ["**"],
        writeGlobs: ["apps/web/**"],
      },
      inputs: ["repo-map.json"],
      outputs: [{ name: "dashboard.patch", type: "git_patch" }],
      acceptanceChecks: [
        {
          type: "command",
          command: "pnpm test web",
          description: "Tests",
          frozen: true,
        },
      ],
      retryPolicy: { maxAttempts: 2 },
      timeoutSeconds: 120,
      verifierPolicy: { required: true, freshSession: true, readonly: true },
    },
    {
      id: "integrate",
      title: "Integrate artifacts",
      kind: "integration",
      objective: "Merge isolated worktrees and resolve contracts.",
      agentSelector: { preferredAgents: ["Mock ACP"] },
      workspace: {
        mode: "integration",
        readGlobs: ["**"],
        writeGlobs: ["src/**"],
      },
      inputs: ["runtime.patch", "dashboard.patch"],
      outputs: [{ name: "integration.diff", type: "diff" }],
      acceptanceChecks: [
        { type: "artifact", description: "Diff", frozen: true },
      ],
      retryPolicy: { maxAttempts: 1 },
      timeoutSeconds: 60,
      verifierPolicy: { required: true, freshSession: true, readonly: true },
    },
    {
      id: "fast_verifier",
      title: "Fast loop verification",
      kind: "verifier",
      objective: "Reject results without sufficient Fast-loop evidence.",
      agentSelector: { preferredAgents: ["Fresh session"] },
      workspace: { mode: "readonly", readGlobs: ["**"], writeGlobs: [] },
      inputs: ["integration.diff"],
      outputs: [{ name: "fast-verification.json", type: "json" }],
      acceptanceChecks: [
        { type: "artifact", description: "Verified", frozen: true },
      ],
      retryPolicy: { maxAttempts: 1 },
      timeoutSeconds: 60,
      verifierPolicy: { required: false, freshSession: true, readonly: true },
    },
    {
      id: "mid_verifier",
      title: "Medium loop verification",
      kind: "verifier",
      objective:
        "Kill a green Fast score when cross-module integrity or rationale audits fail.",
      agentSelector: { preferredAgents: ["Fresh session"] },
      workspace: { mode: "readonly", readGlobs: ["**"], writeGlobs: [] },
      inputs: ["fast-verification.json", "integration.diff"],
      outputs: [{ name: "mid-verification.json", type: "json" }],
      acceptanceChecks: [
        { type: "artifact", description: "Mid verified", frozen: true },
      ],
      retryPolicy: { maxAttempts: 1 },
      timeoutSeconds: 60,
      verifierPolicy: { required: false, freshSession: true, readonly: true },
    },
    {
      id: "acceptance",
      title: "Strategic acceptance",
      kind: "acceptance",
      objective: "Record final acceptance after Medium and Fast loops pass.",
      agentSelector: { preferredAgents: ["Human"] },
      workspace: { mode: "readonly", readGlobs: ["**"], writeGlobs: [] },
      inputs: ["mid-verification.json"],
      outputs: [{ name: "run-report.json", type: "test_report" }],
      acceptanceChecks: [
        { type: "artifact", description: "Accepted", frozen: true },
      ],
      retryPolicy: { maxAttempts: 1 },
      timeoutSeconds: 60,
      verifierPolicy: { required: false, freshSession: true, readonly: true },
    },
  ],
  edges: [
    {
      from: "analyze_repo",
      to: "implement_runtime",
      artifacts: ["repo-map.json"],
    },
    {
      from: "analyze_repo",
      to: "implement_dashboard",
      artifacts: ["repo-map.json"],
    },
    {
      from: "implement_runtime",
      to: "integrate",
      artifacts: ["runtime.patch"],
    },
    {
      from: "implement_dashboard",
      to: "integrate",
      artifacts: ["dashboard.patch"],
    },
    { from: "integrate", to: "fast_verifier", artifacts: ["integration.diff"] },
    {
      from: "fast_verifier",
      to: "mid_verifier",
      artifacts: ["fast-verification.json", "integration.diff"],
    },
    {
      from: "mid_verifier",
      to: "acceptance",
      artifacts: ["mid-verification.json"],
    },
  ],
};
