import Fastify from 'fastify';import websocket from '@fastify/websocket';import fastifyStatic from '@fastify/static';import { randomBytes } from 'node:crypto';import { existsSync,mkdirSync,readFileSync,writeFileSync } from 'node:fs';import { execFileSync } from 'node:child_process';import { dirname,join,resolve } from 'node:path';import { fileURLToPath } from 'node:url';
import { EventStore } from '../../../packages/event-store/src/index.ts';import { GraphRuntime } from '../../../packages/graph-runtime/src/index.ts';import { createDemoSpec } from '../../../packages/graph-runtime/src/demo.ts';import { lintGraphSpec } from '../../../packages/graph-compiler/src/index.ts';import { GraphSpecV1 } from '../../../packages/contracts/src/index.ts';import { discoverAgents } from '../../../packages/agent-registry/src/index.ts';import { inspectRepository } from '../../../packages/repo-intelligence/src/index.ts';
const here=process.env.GRAPH_PLUGIN_ROOT?join(process.env.GRAPH_PLUGIN_ROOT,'runtime'):dirname(fileURLToPath(import.meta.url));const projectRoot=process.env.GRAPH_PLUGIN_ROOT?process.cwd():resolve(here,'../../..');
function ensureDemoRepository(root:string){if(existsSync(join(root,'.git')))return;mkdirSync(root,{recursive:true});const files:Record<string,string>={'package.json':'{"name":"graph-sample","private":true,"scripts":{"test":"node --test"}}\n','test.mjs':"import test from 'node:test';import assert from 'node:assert/strict';test('sample',()=>assert.ok(true));\n",'src/runtime/index.ts':'export const runtimeReady = true;\n','src/dashboard/index.ts':'export const dashboardReady = true;\n'};for(const [path,content] of Object.entries(files)){const target=join(root,path);if(!existsSync(target)){mkdirSync(dirname(target),{recursive:true});writeFileSync(target,content)}}for(const args of [['init','-b','main'],['config','user.email','graph@example.test'],['config','user.name','Graph Demo'],['add','.'],['commit','-m','chore: initialize graph demo']] as const)execFileSync('git',[...args],{cwd:root,stdio:'ignore'})}
export type DaemonOptions={port?:number;host?:string;dataDir?:string;webDist?:string};
export async function startDaemon(options:DaemonOptions={}){const host=options.host??'127.0.0.1',port=options.port??4317,dataDir=options.dataDir??join(projectRoot,'.graph-engineer');mkdirSync(dataDir,{recursive:true});const tokenPath=join(dataDir,'session-token'),token=existsSync(tokenPath)?readFileSync(tokenPath,'utf8').trim():randomBytes(24).toString('base64url');if(!existsSync(tokenPath))writeFileSync(tokenPath,token,{mode:0o600});const store=new EventStore(join(dataDir,'graph-engineer.db'),join(dataDir,'runs')),runtime=new GraphRuntime(store),app=Fastify({logger:false});await app.register(websocket);
  app.addHook('onRequest',async(request,reply)=>{if(request.url==='/api/health'||!request.url.startsWith('/api')&&!request.url.startsWith('/ws'))return;const provided=request.headers.authorization?.replace(/^Bearer\s+/,'')||(request.query as any)?.token;if(provided!==token)return reply.code(401).send({error:'UNAUTHORIZED'})});
  app.get('/api/health',async()=>({status:'ok',host,approvalBoundary:'human_required'}));app.get('/api/session',async()=>({token}));
  app.get('/api/graphs',async()=>store.listGraphs());app.get('/api/graphs/:id',async request=>store.getGraph((request.params as any).id)??{error:'NOT_FOUND'});
  app.post('/api/graphs/validate',async request=>lintGraphSpec(request.body));
  app.post('/api/graphs/demo',async()=>{const root=join(projectRoot,'fixtures/sample-repo');ensureDemoRepository(root);const spec=createDemoSpec(root),validation=lintGraphSpec(spec);if(!validation.valid)throw new Error(`Invalid built-in demo: ${validation.issues.map(issue=>issue.code).join(',')}`);const projectId=store.createProject(root),published=store.publishGraph(projectId,spec);return {...published,projectId,dashboardUrl:`http://${host}:${port}/?token=${token}&graph=${published.graphId}`,validationSummary:{valid:true,errors:0,warnings:validation.issues.filter(issue=>issue.severity==='warning').length},riskSummary:{network:spec.policies.networkPolicy,maxParallel:spec.policies.maxParallel,approval:'required'}}});
  app.post('/api/graphs/publish',async request=>{const body=request.body as any,spec=GraphSpecV1.parse(body.spec),validation=lintGraphSpec(spec);if(!validation.valid)return {error:'VALIDATION_FAILED',validation};const projectId=body.projectId??store.createProject(spec.repository.root),published=store.publishGraph(projectId,spec);return {...published,projectId,dashboardUrl:`http://${host}:${port}/?token=${token}&graph=${published.graphId}`,validationSummary:validation,riskSummary:{network:spec.policies.networkPolicy,maxParallel:spec.policies.maxParallel}}});
  app.post('/api/graphs/:id/amend',async request=>{const graphId=(request.params as any).id,spec=GraphSpecV1.parse((request.body as any).spec),validation=lintGraphSpec(spec);if(!validation.valid)return {error:'VALIDATION_FAILED',validation};return {...store.amendGraph(graphId,spec),validation}});
  app.post('/api/graphs/:id/reject',async request=>{const graph=store.getGraph((request.params as any).id);if(!graph)return {error:'NOT_FOUND'};store.reject(graph.id,'dashboard-human');return {status:'rejected'}});app.post('/api/graphs/:id/approve',async request=>{const graphId=(request.params as any).id,graph=store.getGraph(graphId);if(!graph)return {error:'NOT_FOUND'};store.approve(graph.id,'dashboard-human');const project=(store.db.prepare('SELECT project_id FROM graph_specs WHERE id=?').get(graphId) as any).project_id;const runId=await runtime.start(project,graphId,graph.id,graph.spec);return {status:'running',runId}});
  app.get('/api/runs/:id',async request=>store.getRun((request.params as any).id)??{error:'NOT_FOUND'});app.get('/api/runs/:id/events',async request=>store.eventsAfter((request.params as any).id,Number((request.query as any).after??0)));
  app.post('/api/runs/:id/cancel',async request=>{runtime.cancel((request.params as any).id);return {status:'cancelled'}});app.post('/api/runs/:id/pause',async request=>{runtime.pause((request.params as any).id);return {status:'paused'}});app.post('/api/runs/:id/resume',async request=>{const runId=(request.params as any).id,row=store.getRun(runId);if(!row)return {error:'NOT_FOUND'};runtime.resumePaused(runId);if(!runtime.isActive(runId)){const version=store.getGraphVersion(row.graph_version_id);await runtime.resume((store.db.prepare('SELECT project_id FROM graph_specs WHERE id=?').get(row.graph_id) as any).project_id,runId,version.spec)}return {status:'running'}});app.post('/api/runs/:id/nodes/:node/retry',async request=>{const {id,node}=request.params as any,row=store.getRun(id);if(!row)return {error:'NOT_FOUND'};runtime.retryNode(id,node);if(!runtime.isActive(id)){const version=store.getGraphVersion(row.graph_version_id);await runtime.resume((store.db.prepare('SELECT project_id FROM graph_specs WHERE id=?').get(row.graph_id) as any).project_id,id,version.spec)}return {status:'scheduled'}});app.post('/api/runs/:id/nodes/:node/reassign',async request=>{const {id,node}=request.params as any,agent=(request.body as any).agent;runtime.reassign(id,node,agent);return {status:'updated',agent}});
  app.get('/api/agents',async()=>discoverAgents());app.get('/api/repository',async request=>inspectRepository((request.query as any).root??projectRoot));
  app.get('/ws/runs/:id',{websocket:true},(socket,request)=>{const runId=(request.params as any).id,since=Number((request.query as any).since??0);for(const event of store.eventsAfter(runId,since))socket.send(JSON.stringify(event));const unsubscribe=runtime.subscribe(event=>{if(event.runId===runId&&socket.readyState===1)socket.send(JSON.stringify(event))});socket.on('close',unsubscribe)});
  const webDist=options.webDist??join(projectRoot,'apps/web/dist');if(existsSync(webDist)){await app.register(fastifyStatic,{root:webDist,wildcard:false});app.get('/*',async(_request,reply)=>reply.sendFile('index.html'))}
  await app.listen({host,port});for(const row of store.resumableRuns()){const version=store.getGraphVersion(row.graph_version_id);if(version)void runtime.resume((store.db.prepare('SELECT project_id FROM graph_specs WHERE id=?').get(row.graph_id) as any).project_id,row.id,version.spec)}
  return {app,store,runtime,token,url:`http://${host}:${port}`};}
