import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { execa } from 'execa';
import type { GraphNode, GraphSpec, RunState, TaskEnvelope } from '../../contracts/src/index.ts';
import { compileGraphSpec } from '../../graph-compiler/src/index.ts';
import { EventStore } from '../../event-store/src/index.ts';
import { normalizeAcpUpdate, safeEnvironment } from '../../acp-client/src/index.ts';
import { MockAcpAgent } from '../../mock-acp-agent/src/index.ts';
import { WorktreeManager } from '../../worktree-manager/src/index.ts';
type Listener=(event:ReturnType<EventStore['appendEvent']>)=>void;
const splitCommand=(command:string)=>[...command.matchAll(/"([^"]*)"|'([^']*)'|([^\s]+)/g)].map(match=>match[1]??match[2]??match[3]!).filter(Boolean);
export class GraphRuntime{
  private readonly aborters=new Map<string,AbortController>();private readonly paused=new Set<string>();private readonly listeners=new Set<Listener>();
  constructor(readonly store:EventStore,readonly agent=new MockAcpAgent()){}
  subscribe(listener:Listener){this.listeners.add(listener);return()=>this.listeners.delete(listener)}
  isActive(runId:string){return this.aborters.has(runId)}
  private emit(base:Parameters<EventStore['appendEvent']>[0]){const event=this.store.appendEvent(base);for(const listener of this.listeners)listener(event);return event}
  async start(projectId:string,graphId:string,graphVersionId:string,spec:GraphSpec,runId=`run_${randomUUID()}`){
    compileGraphSpec(spec,async()=>({}));const state:RunState={runId,graphVersion:graphVersionId,repoRef:spec.repository.baseRef,nodeIndex:Object.fromEntries(spec.nodes.map(node=>[node.id,'pending'])),artifactIndex:{},budgetState:{startedAt:new Date().toISOString(),attempts:0},decisionFlags:{approved:true},finalStatus:'running'};
    this.store.createRun(graphId,graphVersionId,state);this.emit({projectId,graphId,runId,nodeId:null,attempt:0,agentId:null,agentSessionId:null,type:'graph.status',payload:{status:'running'}});void this.execute(projectId,graphId,spec,state);return runId;
  }
  async resume(projectId:string,runId:string,spec:GraphSpec){const row=this.store.getRun(runId);if(!row)throw new Error('Run not found');for(const node of spec.nodes)if(['running','ready','retrying'].includes(row.state.nodeIndex[node.id]))row.state.nodeIndex[node.id]='pending';row.state.finalStatus='running';this.store.updateRun(runId,'running',row.state);void this.execute(projectId,row.graph_id,spec,row.state);return runId}
  pause(runId:string){this.paused.add(runId);const row=this.store.getRun(runId);if(row)this.store.updateRun(runId,'paused',{...row.state,finalStatus:'paused'})}
  resumePaused(runId:string){this.paused.delete(runId)}
  retryNode(runId:string,nodeId:string){const row=this.store.getRun(runId);if(!row)throw new Error('Run not found');row.state.nodeIndex[nodeId]='pending';row.state.finalStatus='running';this.store.updateRun(runId,'running',row.state)}
  reassign(runId:string,nodeId:string,agentId:string){const row=this.store.getRun(runId);if(!row)throw new Error('Run not found');row.state.decisionFlags[`agent:${nodeId}`]=agentId;this.store.updateRun(runId,row.status,row.state)}
  cancel(runId:string){this.aborters.get(runId)?.abort();const row=this.store.getRun(runId);if(row){const state={...row.state,finalStatus:'cancelled'};for(const id of Object.keys(state.nodeIndex))if(['pending','ready','running'].includes(state.nodeIndex[id]!))state.nodeIndex[id]='cancelled';this.store.updateRun(runId,'cancelled',state)}}
  private async execute(projectId:string,graphId:string,spec:GraphSpec,state:RunState){const controller=new AbortController();this.aborters.set(state.runId,controller);const incoming=new Map(spec.nodes.map(node=>[node.id,spec.edges.filter(edge=>edge.to===node.id).map(edge=>edge.from)]));
    try{while(true){if(controller.signal.aborted)return;while(this.paused.has(state.runId))await new Promise(resolve=>setTimeout(resolve,25));const pending=spec.nodes.filter(node=>state.nodeIndex[node.id]==='pending');if(!pending.length)break;const ready=pending.filter(node=>(incoming.get(node.id)??[]).every(dep=>state.nodeIndex[dep]==='succeeded'));if(!ready.length)throw new Error('NO_READY_NODES');const batch=ready.slice(0,spec.policies.maxParallel);for(const node of batch){state.nodeIndex[node.id]='ready';this.emit({projectId,graphId,runId:state.runId,nodeId:node.id,attempt:0,agentId:'mock',agentSessionId:null,type:'node.ready',payload:{}})}await Promise.all(batch.map(node=>this.runNode(projectId,graphId,spec,state,node,controller.signal)));this.store.updateRun(state.runId,'running',state)}
      state.finalStatus='completed';this.store.updateRun(state.runId,'completed',state);this.emit({projectId,graphId,runId:state.runId,nodeId:null,attempt:0,agentId:null,agentSessionId:null,type:'run.completed',payload:{artifacts:state.artifactIndex}})
    }catch(error){if(controller.signal.aborted)return;state.finalStatus='failed';this.store.updateRun(state.runId,'failed',state);this.emit({projectId,graphId,runId:state.runId,nodeId:null,attempt:0,agentId:null,agentSessionId:null,type:'run.failed',payload:{error:error instanceof Error?error.message:String(error)}})}finally{this.aborters.delete(state.runId)}}
  private async runNode(projectId:string,graphId:string,spec:GraphSpec,state:RunState,node:GraphNode,signal:AbortSignal){const manager=new WorktreeManager(spec.repository.root),worktree=node.workspace.mode==='readonly'?null:await manager.create(projectId,state.runId,node.workspace.mode==='integration'?'integration':node.id,spec.repository.baseRef);if(worktree&&node.workspace.mode==='integration'){const commits=await Promise.all(Object.entries(state.artifactIndex).filter(([name])=>name.startsWith('commit:')).map(([,artifact])=>readFile(artifact.path,'utf8')));const integration=await manager.integrate(worktree.path,commits.map(commit=>commit.trim()));if(!integration.success)throw new Error(`INTEGRATION_CONFLICT:${integration.conflict}`)}for(let attempt=1;attempt<=node.retryPolicy.maxAttempts;attempt++){state.budgetState.attempts++;const workerSession=this.store.createSession(state.runId,node.id,attempt,'worker');state.nodeIndex[node.id]='running';this.store.upsertNodeRun(state.runId,node.id,attempt,'running',workerSession);this.emit({projectId,graphId,runId:state.runId,nodeId:node.id,attempt,agentId:'mock',agentSessionId:workerSession,type:'node.status',payload:{status:'running'}});
      const envelope:TaskEnvelope={runId:state.runId,nodeId:node.id,attempt,objective:node.objective,workspace:worktree?.path??spec.repository.root,readGlobs:node.workspace.readGlobs,writeGlobs:node.workspace.writeGlobs,inputArtifactPaths:node.inputs.map(name=>state.artifactIndex[name]?.path).filter((value):value is string=>Boolean(value)),outputContract:node.outputs,acceptanceCommands:node.acceptanceChecks.filter(check=>check.type==='command'&&check.command).map(check=>check.command!),timeoutSeconds:node.timeoutSeconds,prohibitedOperations:['git push','deploy','publish','delete','payment','nested subagents']};
      const timeout=AbortSignal.timeout(node.timeoutSeconds*1000);const combined=AbortSignal.any([signal,timeout]);const result=await this.agent.execute(envelope,workerSession,update=>{const normalized=normalizeAcpUpdate(update);this.emit({projectId,graphId,runId:state.runId,nodeId:node.id,attempt,agentId:'mock',agentSessionId:workerSession,...normalized})},combined);
      if(result.status==='cancelled')throw new Error('NODE_CANCELLED');this.emit({projectId,graphId,runId:state.runId,nodeId:node.id,attempt,agentId:'mock',agentSessionId:workerSession,type:'node.check.started',payload:{commands:envelope.acceptanceCommands}});let physicalPassed=true;if(worktree){const changed=await manager.changedFiles(worktree.path),scope=manager.verifyWriteGlobs(changed,node.workspace.writeGlobs);physicalPassed=scope.valid;const diffPath=join(this.store.root,state.runId,'diffs',`${node.id}.patch`);await manager.collectDiff(worktree.path,diffPath);const diffArtifact=this.store.writeArtifact(state.runId,node.id,`${node.id}.patch`,await readFile(diffPath,'utf8'));state.artifactIndex[`diff:${node.id}`]=diffArtifact;this.emit({projectId,graphId,runId:state.runId,nodeId:node.id,attempt,agentId:'git',agentSessionId:null,type:'agent.diff',payload:{changedFiles:changed,outsideWriteScope:scope.outside,patch:diffArtifact.path}})}for(const command of envelope.acceptanceCommands){const [binary,...args]=splitCommand(command);if(!binary){physicalPassed=false;continue}const check=await execa(binary,args,{cwd:worktree?.path??spec.repository.root,env:safeEnvironment(),timeout:node.timeoutSeconds*1000,reject:false});this.emit({projectId,graphId,runId:state.runId,nodeId:node.id,attempt,agentId:'physical-check',agentSessionId:null,type:'agent.terminal.delta',payload:{delta:`$ ${command}\n${check.stdout}\n${check.stderr}`}});if(check.exitCode!==0)physicalPassed=false}this.emit({projectId,graphId,runId:state.runId,nodeId:node.id,attempt,agentId:'mock',agentSessionId:workerSession,type:'node.check.completed',payload:{passed:physicalPassed}});
      const artifactNames:string[]=[];for(const output of node.outputs){const content=output.name==='run-report.json'?{runId:state.runId,status:'completed',finalBranch:`graph/${state.runId}/integration`,diffs:Object.entries(state.artifactIndex).filter(([name])=>name.startsWith('diff:')).map(([name,value])=>({nodeId:name.slice(5),...value})),tests:envelope.acceptanceCommands.map(command=>({command,passed:physicalPassed})),attempts:state.budgetState.attempts}:{nodeId:node.id,attempt,summary:result.summary};const artifact=this.store.writeArtifact(state.runId,node.id,output.name,JSON.stringify(content,null,2));state.artifactIndex[output.name]=artifact;artifactNames.push(output.name);this.emit({projectId,graphId,runId:state.runId,nodeId:node.id,attempt,agentId:'mock',agentSessionId:workerSession,type:'artifact.created',payload:{name:output.name,...artifact}})}
      const verifierSession=this.store.createSession(state.runId,node.id,attempt,'verifier');const verification=physicalPassed?await this.agent.verify(node.id,attempt,verifierSession,artifactNames):{accepted:false,sessionId:verifierSession,reasons:['Physical acceptance command failed'],checkedArtifacts:artifactNames};if(!verification.accepted){this.store.upsertNodeRun(state.runId,node.id,attempt,'verification_failed',workerSession);this.emit({projectId,graphId,runId:state.runId,nodeId:node.id,attempt,agentId:'mock',agentSessionId:verifierSession,type:'node.verification.failed',payload:{reasons:verification.reasons}});if(attempt<node.retryPolicy.maxAttempts){this.emit({projectId,graphId,runId:state.runId,nodeId:node.id,attempt,agentId:'mock',agentSessionId:null,type:'node.retry.scheduled',payload:{nextAttempt:attempt+1}});continue}throw new Error(`GIVE_UP:${node.id}`)}
      if(worktree){const commit=await manager.commit(worktree.path,`graph(${node.id}): attempt ${attempt}`),commitArtifact=this.store.writeArtifact(state.runId,node.id,`${node.id}.commit`,commit);state.artifactIndex[`commit:${node.id}`]=commitArtifact;await manager.cleanup(worktree.path)}state.nodeIndex[node.id]='succeeded';this.store.upsertNodeRun(state.runId,node.id,attempt,'succeeded',workerSession);this.store.updateRun(state.runId,'running',state);this.emit({projectId,graphId,runId:state.runId,nodeId:node.id,attempt,agentId:'mock',agentSessionId:workerSession,type:'node.status',payload:{status:'succeeded',verifierSession}});return}}
}
