#!/usr/bin/env node
import { Command } from 'commander';import { existsSync,mkdirSync,readFileSync } from 'node:fs';import { join,resolve } from 'node:path';import { discoverAgents } from '../../../packages/agent-registry/src/index.ts';import { inspectRepository } from '../../../packages/repo-intelligence/src/index.ts';import { createDemoSpec } from '../../../packages/graph-runtime/src/demo.ts';import { lintGraphSpec } from '../../../packages/graph-compiler/src/index.ts';import { startDaemon } from '../../daemon/src/server.ts';
const program=new Command().name('graphctl').description('Local Graph Engineering compiler and runtime').version('0.1.0');const base=()=>process.env.GRAPHD_URL??'http://127.0.0.1:4317';const dataDir=()=>resolve(process.env.GRAPH_ENGINEER_HOME??'.graph-engineer');
function token(){const path=join(dataDir(),'session-token');return existsSync(path)?readFileSync(path,'utf8').trim():''}async function api(path:string,init:RequestInit={}){const headers:Record<string,string>={authorization:`Bearer ${token()}`,...(init.headers as Record<string,string>|undefined)};if(init.body)headers['content-type']='application/json';const response=await fetch(`${base()}${path}`,{...init,headers});if(!response.ok)throw new Error(`${response.status} ${await response.text()}`);return response.json() as Promise<any>}
program.command('init').description('Initialize local Graph Engineer state').action(()=>{mkdirSync(dataDir(),{recursive:true});console.log(`Initialized ${dataDir()}`)});
program.command('doctor').description('Inspect repository, daemon, and available agents').action(async()=>{const agents=await discoverAgents(),repo=await inspectRepository(process.cwd());let daemon='offline';try{daemon=(await (await fetch(`${base()}/api/health`)).json()).status}catch{}console.log(JSON.stringify({daemon,repository:{root:repo.root,dirty:repo.git.dirty,packageManager:repo.packageManager},agents},null,2))});
program.command('agents').action(async()=>console.log(JSON.stringify(await discoverAgents(),null,2)));
program.command('plan').argument('<goal>').action(async goal=>{const spec=createDemoSpec(process.cwd(),goal),validation=lintGraphSpec(spec);if(!validation.valid)throw new Error('Generated GraphSpec failed validation');console.log(JSON.stringify(await api('/api/graphs/publish',{method:'POST',body:JSON.stringify({spec})}),null,2))});
program.command('graphs').action(async()=>console.log(JSON.stringify(await api('/api/graphs'),null,2)));
const graph=program.command('graph');graph.command('show').argument('<graph-id>').action(async id=>console.log(JSON.stringify(await api(`/api/graphs/${id}`),null,2)));graph.command('approve').argument('<graph-id>').action(async id=>console.log(JSON.stringify(await api(`/api/graphs/${id}/approve`,{method:'POST'}),null,2)));
const run=program.command('run');run.command('show').argument('<run-id>').action(async id=>console.log(JSON.stringify(await api(`/api/runs/${id}`),null,2)));for(const verb of ['cancel','resume'] as const)run.command(verb).argument('<run-id>').action(async id=>console.log(JSON.stringify(await api(`/api/runs/${id}/${verb}`,{method:'POST'}),null,2)));
program.command('open').action(()=>console.log(`${base()}/?token=${token()}`));
program.command('demo').option('--approve','approve the draft through the explicit CLI boundary').option('--wait','wait for completion and print the report').action(async options=>{let owned:Awaited<ReturnType<typeof startDaemon>>|null=null;try{await fetch(`${base()}/api/health`)}catch{owned=await startDaemon({dataDir:dataDir()})}const draft=await api('/api/graphs/demo',{method:'POST'});console.log(`Draft Graph: ${draft.graphId}`);console.log(`Dashboard: ${draft.dashboardUrl}`);console.log('Status: awaiting human approval');if(!options.approve){console.log(`Approve with: graphctl graph approve ${draft.graphId}`);return}const approved=await api(`/api/graphs/${draft.graphId}/approve`,{method:'POST'});console.log(`Run: ${approved.runId}`);if(options.wait){let status;do{await new Promise(resolve=>setTimeout(resolve,50));status=await api(`/api/runs/${approved.runId}`)}while(['pending','running','paused'].includes(status.status));const events=await api(`/api/runs/${approved.runId}/events`),finalArtifact=status.state.artifactIndex['run-report.json'],report=finalArtifact?JSON.parse(readFileSync(finalArtifact.path,'utf8')):null;console.log(JSON.stringify({status:status.status,finalArtifact,report,events:events.length,retried:events.some((event:any)=>event.type==='node.retry.scheduled')},null,2));if(owned){await owned.app.close();owned.store.close()}}});
await program.parseAsync();
